### ISSUE TITLE
Why install cowsay as dependency?

### ISSUE THREAD

**Issue by gbraad** [eRadical/ansible-my-fedora-workstation#1]
https://github.com/eRadical/ansible-my-fedora-workstation/blob/8859aae21e5b66e11fdc9fcede9c382a07fad479/configure-fedora#L3

**Comment by eRadical** [comment]
Hi Gerard,

In `ansible.cfg` I have `cow_selection = random` thus at the time ansible starts I want cowsay to be already available on the machine.

Think of it as „Gimme, gimme, gimme a man after midnight ” thing... but more visible.
